{{- if .Values.elasticsearch_exporter.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-exporter-{{ .Values.elasticsearch_exporter.name }}
  namespace: elastiflow
  labels:
    system: openstack
    service: audit

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        component: es-exporter-{{ .Values.elasticsearch_exporter.name }}
    spec:
      nodeSelector:
        zone: farm
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: elasticsearch-exporter
          image: "{{ .Values.elasticsearch_exporter.image.repo }}:{{ .Values.elasticsearch_exporter.image.tag }}"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/elasticsearch_exporter", "--es.all", "--web.listen-address", ":{{ .Values.elasticsearch_exporter.listen_port }}", "--es.cluster_settings" ]
          ports:
            - name: metrics
              containerPort: {{ .Values.elasticsearch_exporter.listen_port }}
          env:
            - name: ES_URI
              value: {{ .Values.elasticsearch_exporter.es.uri }}
          securityContext:
            capabilities:
              drop:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - NET_RAW
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
{{ end -}}
