kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: vrops-exporter 
  namespace: infra-monitoring
spec:
  selector:
    matchLabels:
      app: vrops-exporter 
      type: exporter
  template:
    metadata:
      labels:
        app: vrops-exporter
        type: exporter
    spec:
      containers:
         - name: vrops-exporter
           image: {{ required ".Values.vrops.image.imageRegistry variable missing" .Values.vrops.image.imageRegistry }}/{{ required ".Values.vrops.image.namespace variable missing" .Values.vrops.image.namespace }}/{{ required ".Values.vrops.image.name variable missing" .Values.vrops.image.name }}:{{ required ".Values.vrops.image.tag variable missing" .Values.vrops.image.tag }}
           ports:
             - name: metrics
               containerPort: {{ required ".Values.vrops.port missing" .Values.vrops.port_number }}
           command:
             - ./exporter.py
           env:
           - name: PORT
             value: {{ required ".Values.vrops.port_number missing" .Values.vrops.port_number | quote }}
           - name: DEBUG
             value: {{ .Values.vrops.debug | quote }}
           - name: INVENTORY
             value: vrops-inventory
           resources:
             limits:
               memory: 500Mi
               cpu: 300m
             requests:
               memory: 300Mi
               cpu: 150m
           livenessProbe:
             httpGet:
               path: /metrics
               port: {{ required ".Values.vrops.port_number missing" .Values.vrops.port_number }}
             initialDelaySeconds: 300
             timeoutSeconds: 180
             periodSeconds: 600
