dependencies:
  - name: elasticsearch
    alias: elasticsearch
    version: 7.6.1
    repository: file://vendor/elasticsearch

  - name: kibana
    repository: file://vendor/kibana
    version: 7.6.1

  - name: logstash
    repository: file://vendor/logstash
    version: 7.6.1