exporter:
  image:
    name: apic-exporter
    tag: DEFINED-IN-PIPELINE
  log_level: ERROR
  namespace: infra-monitoring
  prometheus:
    port: 9102
    scrape: true
    name: infra-collector
  resources:
    limits:
      memory: 500Mi
      cpu: 300m
    requests:
      memory: 300Mi
      cpu: 150m
alerts:
  enabled: true
  prometheus: infra-collector