apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: blackbox-tests-canary-nova

data:
  os.password: {{ .Values.global.openstack.users.admin.password | b64enc }}
  cc.password: {{ .Values.global.openstack.users.ccadmin.password | b64enc }}
  vc.password: {{ .Values.global.vcenter.password | b64enc }}
  os.profiler.hmacs: {{ if .Values.global.osprofiler.enabled }}{{ .Values.global.osprofiler.hmac_keys | b64enc }}{{ end }}
  jump.key: {{ .Values.global.jump.key | b64enc }}
