dependencies:
  - condition: conntrack-nanny.enabled
    name: conntrack-nanny
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.0

  - name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.35.0
